In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [60]:
df_tr = pd.read_csv("data/train.csv").drop(columns = "id")
df_ts = pd.read_csv("data/test.csv").drop(columns = "id")

df_ts

,annual_income,debt_to_income_ratio,credit_score,loan_amount,interest_rate,gender,marital_status,education_level,employment_status,loan_purpose,grade_subgrade
0,28781.05,0.049,626,11461.42,14.73,Female,Single,High School,Employed,Other,D5
1,46626.39,0.093,732,15492.25,12.85,Female,Married,Master's,Employed,Other,C1
2,54954.89,0.367,611,3796.41,13.29,Male,Single,Bachelor's,Employed,Debt consolidation,D1
3,25644.63,0.110,671,6574.30,9.57,Female,Single,Bachelor's,Employed,Debt consolidation,C3
4,25169.64,0.081,688,17696.89,12.80,Female,Married,PhD,Employed,Business,C1
...,...,...,...,...,...,...,...,...,...,...,...
254564,92835.97,0.068,744,29704.00,13.48,Female,Single,Bachelor's,Employed,Debt consolidation,B2
254565,48846.47,0.091,634,20284.33,9.58,Female,Married,High School,Employed,Debt consolidation,D4
254566,20668.52,0.096,718,26387.55,9.00,Male,Single,Master's,Employed,Debt consolidation,C4
254567,34105.09,0.094,739,11107.36,9.81,Male,Single,Bachelor's,Employed,Business,C2
254568,45627.53,0.118,624,19246.14,11.64,Female,Married,High School,Employed,Car,D3

In [61]:
df_tr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 593994 entries, 0 to 593993
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   annual_income         593994 non-null  float64
 1   debt_to_income_ratio  593994 non-null  float64
 2   credit_score          593994 non-null  int64
 3   loan_amount           593994 non-null  float64
 4   interest_rate         593994 non-null  float64
 5   gender                593994 non-null  object
 6   marital_status        593994 non-null  object
 7   education_level       593994 non-null  object
 8   employment_status     593994 non-null  object
 9   loan_purpose          593994 non-null  object
 10  grade_subgrade        593994 non-null  object
 11  loan_paid_back        593994 non-null  float64
dtypes: float64(5), int64(1), object(6)
memory usage: 54.4+ MB

In [77]:
df_tr["loan_paid_back"].value_counts()

loan_paid_back
1.0    474494
0.0    119500
Name: count, dtype: int64

In [62]:
df_tr['grade'] = df_tr['grade_subgrade'].str[0]
df_tr['subgrade'] = df_tr['grade_subgrade'].str[1].astype(int)

df_ts['grade'] = df_ts['grade_subgrade'].str[0]
df_ts['subgrade'] = df_ts['grade_subgrade'].str[1].astype(int)

In [63]:
print(df_tr[['grade_subgrade', 'grade', 'subgrade']].head())

  grade_subgrade grade  subgrade
0             C3     C         3
1             D3     D         3
2             C5     C         5
3             F1     F         1
4             D1     D         1

In [64]:
df_tr = df_tr.drop(columns=["grade_subgrade"])
df_ts = df_ts.drop(columns=["grade_subgrade"])

In [65]:
# map some shit with binary

df_ts["gender"] = df_ts["gender"].map({"Male": 1, "Female": 0, "Other": -1})
df_tr["gender"] = df_tr["gender"].map({"Male": 1, "Female": 0, "Other": -1})

df_ts["marital_status"] = df_ts["marital_status"].map({"Married": 1, "Single": 0, "Widowed": 0, "Divorced": -1})
df_tr["marital_status"] = df_tr["marital_status"].map({"Married": 1, "Single": 0, "Widowed": 0, "Divorced": -1})



order = ["Other", "High School", "Bachelor's", "Master's", "PhD"]
df_tr["education_level"] = (
    pd.Categorical(df_tr["education_level"], categories=order, ordered=True)
    .codes
)
df_ts["education_level"] = (
    pd.Categorical(df_ts["education_level"], categories=order, ordered=True)
    .codes
)



order = ['G', 'F', 'E', 'D', 'C', 'B', 'A']
df_tr["grade"] = (
    pd.Categorical(df_tr["grade"], categories=order, ordered=True)
    .codes
)
df_ts["grade"] = (
    pd.Categorical(df_ts["grade"], categories=order, ordered=True)
    .codes
)

In [66]:
#get dummy of some categorical shit

dummies = pd.get_dummies(df_tr["employment_status"], dtype=int)
df_tr = df_tr.drop(columns=["employment_status"]).join(dummies)
dummies = pd.get_dummies(df_ts["employment_status"], dtype=int)
df_ts = df_ts.drop(columns=["employment_status"]).join(dummies)



dummies = pd.get_dummies(df_tr["loan_purpose"], dtype=int)
df_tr = df_tr.drop(columns=["loan_purpose"]).join(dummies)
dummies = pd.get_dummies(df_ts["loan_purpose"], dtype=int)
df_ts = df_ts.drop(columns=["loan_purpose"]).join(dummies)


df_tr

,annual_income,debt_to_income_ratio,credit_score,loan_amount,interest_rate,gender,marital_status,education_level,loan_paid_back,grade,...,Student,Unemployed,Business,Car,Debt consolidation,Education,Home,Medical,Other,Vacation
0,29367.99,0.084,736,2528.42,13.67,0,0,1,1.0,4,...,0,0,0,0,0,0,0,0,1,0
1,22108.02,0.166,636,4593.10,12.92,1,1,3,0.0,3,...,0,0,0,0,1,0,0,0,0,0
2,49566.20,0.097,694,17005.15,9.76,1,0,1,1.0,4,...,0,0,0,0,1,0,0,0,0,0
3,46858.25,0.065,533,4682.48,16.10,0,0,1,1.0,1,...,0,0,0,0,1,0,0,0,0,0
4,25496.70,0.053,665,12184.43,10.21,1,1,1,1.0,3,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593989,23004.26,0.152,703,20958.37,10.92,0,0,1,1.0,4,...,0,0,1,0,0,0,0,0,0,0
593990,35289.43,0.105,559,3257.24,14.62,1,0,2,1.0,1,...,0,0,0,0,1,0,0,0,0,0
593991,47112.64,0.072,675,929.27,14.13,0,1,2,1.0,4,...,0,0,0,0,1,0,0,0,0,0
593992,76748.44,0.067,740,16290.40,9.87,1,0,2,1.0,5,...,0,0,0,0,1,0,0,0,0,0
593993,48959.52,0.096,752,7707.73,10.31,1,1,1,1.0,5,...,0,0,0,0,0,1,0,0,0,0

In [67]:
df_tr['loan_to_income_ratio'] = df_tr['loan_amount'] / df_tr['annual_income']
df_tr['disposable_income'] = df_tr['annual_income'] * (1 - df_tr['debt_to_income_ratio'])
df_tr['monthly_payment_capacity'] = (df_tr['annual_income'] / 12) * (1 - df_tr['debt_to_income_ratio']) * 0.3
df_tr['total_interest_cost'] = df_tr['loan_amount'] * df_tr['interest_rate'] / 100
df_tr['interest_to_principal_ratio'] = df_tr['total_interest_cost'] / df_tr['loan_amount']
df_tr['loan_burden_index'] = (df_tr['loan_amount'] * df_tr['interest_rate'] / 100) / df_tr['annual_income']

In [68]:
df_ts['loan_to_income_ratio'] = df_ts['loan_amount'] / df_ts['annual_income']
df_ts['disposable_income'] = df_ts['annual_income'] * (1 - df_ts['debt_to_income_ratio'])
df_ts['monthly_payment_capacity'] = (df_ts['annual_income'] / 12) * (1 - df_ts['debt_to_income_ratio']) * 0.3
df_ts['total_interest_cost'] = df_ts['loan_amount'] * df_ts['interest_rate']/ 100
df_ts['interest_to_principal_ratio'] = df_ts['total_interest_cost'] / df_ts['loan_amount']
df_ts['loan_burden_index'] = (df_ts['loan_amount'] * df_ts['interest_rate'] / 100) / df_ts['annual_income']

In [69]:
# normalize numeric shit
from sklearn.preprocessing import StandardScaler

normalize_cols = [
    "annual_income",
    "debt_to_income_ratio",
    "credit_score",
    "loan_amount",
    "interest_rate",
    "loan_to_income_ratio",
    "disposable_income",
    "monthly_payment_capacity",
    "total_interest_cost",
    "interest_to_principal_ratio",
    "loan_burden_index"
]

scaler = StandardScaler()
df_tr[normalize_cols] = scaler.fit_transform(df_tr[normalize_cols])
df_ts[normalize_cols] = scaler.fit_transform(df_ts[normalize_cols])

In [70]:
from helper_functions import plot_predictions, plot_decision_boundary
def plot(X, y, model= None):
        if model is not None:
            plt.figure(figsize=(16, 8))
            plt.subplot(1, 2, 1)
            plt.title("Train")
            plot_decision_boundary(model, X, y)
        else:
            plt.figure(figsize=(12,12))
            plt.scatter(X[:,0], X[:,1], c=y, cmap=plt.cm.RdYlBu)

In [71]:
from sklearn.model_selection import train_test_split

X = df_tr.drop(columns=["loan_paid_back"])
y = df_tr["loan_paid_back"]

X_train, X_val, y_train, y_val = train_test_split(X,y,test_size=0.05,random_state=42)

len(X_train), len(X_val), len(y_train), len(X_val)

(564294, 29700, 564294, 29700)

In [72]:
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report


cb_model = CatBoostClassifier(
    iterations=600,
    learning_rate=0.1,
    depth=6,
    l2_leaf_reg=7.011376544533179,
    border_count=150,
    random_seed=42,
    verbose=100
)

cb_model.fit(X_train, y_train, eval_set=(X_val, y_val), use_best_model=True)

0:	learn: 0.5792564	test: 0.5789819	best: 0.5789819 (0)	total: 86.3ms	remaining: 51.7s
100:	learn: 0.2520921	test: 0.2514435	best: 0.2514435 (100)	total: 9.29s	remaining: 45.9s
200:	learn: 0.2490974	test: 0.2492495	best: 0.2492477 (199)	total: 18.7s	remaining: 37.2s
300:	learn: 0.2470290	test: 0.2480416	best: 0.2480411 (299)	total: 29.9s	remaining: 29.7s
400:	learn: 0.2453985	test: 0.2474343	best: 0.2474343 (400)	total: 42.3s	remaining: 21s
500:	learn: 0.2439905	test: 0.2470310	best: 0.2470275 (496)	total: 54.6s	remaining: 10.8s
599:	learn: 0.2427705	test: 0.2466889	best: 0.2466889 (599)	total: 1m 6s	remaining: 0us

bestTest = 0.2466888543
bestIteration = 599

In [74]:
preds = cb_model.predict(X_val)
preds_tr = cb_model.predict(X_train)

acc = accuracy_score(y_val, preds)
acc_tr = accuracy_score(y_train, preds_tr)

print("\nCatBoost Evaluation")
print(f"test set: {acc:.4f} | train set: {acc_tr:.4f}")
print(classification_report(y_val, preds))

CatBoost Evaluation
test set: 0.9029 | train set: 0.9074
              precision    recall  f1-score   support

         0.0       0.88      0.60      0.72      6035
         1.0       0.91      0.98      0.94     23665

    accuracy                           0.90     29700
   macro avg       0.89      0.79      0.83     29700
weighted avg       0.90      0.90      0.90     29700

In [75]:
y_pred_ts = cb_model.predict(df_ts)
sub = pd.DataFrame({"loan_paid_back": y_pred_ts})
sub["loan_paid_back"].value_counts()

loan_paid_back
1.0    219920
0.0     34649
Name: count, dtype: int64